# Define the base image
FROM ubuntu:14.04

# Basic setup
RUN apt-get update
RUN apt-get install perl

# Create test user
RUN useradd -ms /bin/bash isisuser

# Copy limits.conf
COPY ulimits/limits.conf /etc/security/limits.conf

# Copy apparmor configuration
COPY apparmor/home.isisuser.testsource /etc/apparmor.d/

# Copy Runner script and change the owner
COPY TestUtils/Runner.pm /home/isisuser/
RUN chown isisuser: /home/isisuser/Runner.pm
